name: Автоматический деплой

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Проверка кода
      uses: actions/checkout@v3
      
    - name: Настройка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Настройка SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Добавление сервера в известные хосты
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        
    - name: Деплой на сервер
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PATH: ${{ secrets.SERVER_PATH }}
      run: |
        # Создание архива проекта
        tar -czf telegram_bot.tar.gz --exclude='.git' --exclude='venv' --exclude='env' --exclude='*.env' --exclude='*.log' --exclude='*.tmp' .
        
        # Копирование архива на сервер
        scp telegram_bot.tar.gz ${SERVER_USER}@${SERVER_HOST}:${SERVER_PATH}
        
        # Выполнение команд на сервере
        ssh ${SERVER_USER}@${SERVER_HOST} << 'EOF'
          cd "${{ secrets.SERVER_PATH }}"
          tar -xzf telegram_bot.tar.gz
          rm telegram_bot.tar.gz
          
          # Проверка наличия Docker и Docker Compose
          if ! command -v docker &> /dev/null || ! command -v docker-compose &> /dev/null; then
            echo "Ошибка: Docker и/или Docker Compose не установлены на сервере."
            exit 1
          fi
          
          # Запуск контейнеров
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
          
          # Проверка статуса контейнеров
          docker-compose ps
        EOF